---
title: "Rejoindre le laboratoire"
description: |
lang: fr  

output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---
<!-- ff -->
* Nous sommes amicaux, gentils, collaboratifs, personnalisés, accommodants, inclusifs, solidaires et dédiés au progrès scientifique et individuel. Et amusants. Tous sont les bienvenus, et en particulier ceux qui ne se sont pas sentis les bienvenus par le passé. Nous valorisons la diversité.

* En ce moment, nous recherchons particulièrement des personnes (à tous les niveaux) qui s'intéressent à l'analyse quantitative des données neuronales et aux neurosciences computationnelles, et qui possèdent des compétences et des antécédents adaptés à ces domaines.

* Si vous êtes intéressé, veuillez envoyer votre CV et votre relevé de notes à cette [adresse](mailto : m2b3.lab@mcgill.ca), ainsi qu'une brève introduction expliquant pourquoi vous êtes intéressé par le laboratoire.

### Etudiants de Premier Cycle

* Les étudiants de premier cycle de McGill sont les bienvenus en tant que chercheurs indépendants encadrés, ou dans le cadre de cours de recherche comme PHGY 396/461, COGS 444 D1/D2, PSYC 395/494, COMP 401, NSCI 420 etc. Il existe des projets d'analyse de données/théorie basés sur la programmation pour ceux qui ont des compétences en programmation et des projets basés sur la psychophysique humaine pour ceux qui s'y intéressent. Il y a également des projets liés à la musique. Veuillez envoyer votre CV et votre relevé de notes à cette adresse [e-mail](mailto : m2b3.lab@mcgill.ca).

* Il existe plusieurs bourses possibles pour les étudiants internationaux de premier cycle issus de pays sous-représentés, notamment [ici](https://www.educanada.ca/scholarships-bourses/can/institutions/asean-anase.aspx?lang=eng), [ici](https://www.educanada.ca/scholarships-bourses/can/institutions/study-in-canada-sep-etudes-au-canada-pct.aspx?lang=eng), et [ici](https://www.educanada.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng). 

### Maîtrise et Doctorat

* Les étudiants diplômés potentiels (maîtrise et doctorat) peuvent poser leur candidature via le programme d'études supérieures en physiologie ou le programme IPN. Pour certains candidats, le programme QLS peut également être une bonne option. McGill permet aux candidats de s'inscrire à deux programmes avec des frais de demande uniques.  Nous sommes particulièrement intéressés par les personnes qui sont à l'aise avec la pensée quantitative ; toutefois, ce n'est pas un critère nécessaire et, selon les projets disponibles, des places pour les personnes ayant d'autres compétences peuvent également être disponibles.

* Pour les étudiants diplômés potentiels (maîtrise et doctorat), et en particulier les étudiants diplômés potentiels internationaux, il y a de très bonnes raisons de postuler via le programme de physiologie - ce programme est très flexible, très bien noté et offre essentiellement la même expérience d'études supérieures (ou mieux) par rapport aux autres possibilités offertes à McGill. Vous pouvez postuler à deux programmes d'études supérieures à McGill en payant un seul droit de candidature. Étudiants internationaux, veuillez noter que le programme de physiologie a des dates limites beaucoup plus rapprochées - consultez [cette page web](https://www.mcgill.ca/gradapplicants/programs/physiology) pour plus de détails (vers la fin).

* Il existe plusieurs bourses destinées aux étudiants de troisième cycle originaires de certains pays. Des exemples spécifiques, tirés de [cette source](https://www.mcgill.ca/gps/funding/international-student-postdoctoral-funding-opportunities/international), sont la Grèce, la Chine, le Mexique, les Émirats arabes unis, le Ghana, la Tunisie, l'Égypte, le Chili et des exemptions de frais différentiels pour les étudiants d'Inde, du Brésil, etc. Les étudiants français bénéficient d'une exonération totale des droits différentiels. Il existe des possibilités pour les étudiants d'un nombre encore plus grand de pays énumérés [ici](https://www.mcgill.ca/gps/funding/international-student-postdoctoral-funding-opportunities/opportunities-available-through-international-agencies).

* Les étudiants du programme McGill-UESTC IPN-China sont les bienvenus. Le laboratoire participe activement à ce programme.

### Postdocs et associés de recherche

* Les disponibilités pour postdocs dépendent de la situation financière du laboratoire, de l'éligibilité aux subventions postdocs externes, etc. Il existe une variété d'options qui changent d'année en année. Les demandes de renseignements sont les bienvenues, tout comme le parrainage de bourses internationales telles que [HFSP](https://www.hfsp.org/funding/hfsp-funding/postdoctoral-fellowships), etc.